[package]
name = "image-provider"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum-map = { version = "2.4.2" }
image = { version = "0.24.5", optional = true, default-features = false }
derivative = { version = "2.2.0", optional = true, features = ["use_core"] }

[features]
default = ["imagebuffer_display", "reader"]

imagebuffer_display = ["std", "image", "image/png"]
reader = ["derivative"]

alloc = []
std = ["alloc"]
