[package]
name = "image-provider"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum-map = { version = "2.4.2" }
image = { version = "0.24.5", optional = true, default-features = false }

[features]
default = ["std", "imagebuffer_display"]

imagebuffer_display = ["image", "image/png"]

alloc = []
std = ["alloc"]
