[package]
name = "image-provider"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum-map = { version = "2.4.2" }

[features]
default = ["std"]

alloc = []
std = ["alloc"]
